export const incidentConstants = {
  GET_INCIDENTS: "GET_INCIDENTS",
  GET_INCIDENT: "GET_INCIDENT",
  DELETE_INCIDENT: "DELETE_INCIDENT",
  ADD_INCIDENT: "ADD_INCIDENT",
  UPDATE_INCIDENT: "UPDATE_INCIDENT"
};
